services:
  - type: redis
    name: prototype-for-sean-redis
    region: oregon
    plan: starter # use a plan with persistence
    maxmemoryPolicy: noeviction # recommended policy for queues
    ipAllowList: [] # only allow internal connections
  - type: web
    runtime: node
    name: prototype-for-sean-web
    region: oregon
    repo: https://github.com/SupaLlama/prototype-for-sean-frontend
    buildCommand: "npm install; npm run build" 
    startCommand: "npm run start"
    envVars:
      - key: FASTAPI_URL
        value: http://prototype-for-sean-api:10000
  - type: pserv
    runtime: python
    name: prototype-for-sean-api
    region: oregon
    repo: https://github.com/SupaLlama/prototype-for-sean-backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          name: prototype-for-sean-redis
          type: redis
          property: connectionString
      - key: CELERY_RESULT_URL
        fromService:
          name: prototype-for-sean-redis
          type: redis
          property: connectionString
  - type: worker
    runtime: python
    name: prototype-for-sean-worker
    region: oregon
    repo: https://github.com/SupaLlama/prototype-for-sean-backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A main.celery worker --loglevel=info --concurrency 2"
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          name: prototype-for-sean-redis
          type: redis
          property: connectionString
      - key: CELERY_RESULT_URL
        fromService:
          name: prototype-for-sean-redis
          type: redis
          property: connectionString